travis:
  secure:
    BINSTAR_TOKEN: RWiNahgf/1Zib1kBBh7zfdcSuYXIppXw1aMKv02cjFP/UPy+s1wVIyhN4gbT9CWrl7pmOZmZ+/N+YOLh3ptZ6wCVOhQy7YJnYnJc7vSmsOYZM+3k3aUeKKklhivoQJXIgh4WuQmsk82+FCyFmckfKyWHWDdov8yFYNW9cxuUblXHS16wlldK+71867lP+rTtp17/H0I0ajGQNJndoYGy/69i9HZs8Ryii2kG6bJ671udfJBOuI4/m3UypXqCiCaIC5XAFkfAvcDqTLHZZEvJQwJFiC02R+LSbrAym/C8BqBZEPU3/eDJIf8X3tvZHJIOKOE01JfhfnjosRVE+lYNBWV3puZ74BUmUbXbFpVxsL88utWdkCPm2N0IWsQUhHgHl14xFBt4anYmllkwYwc5pLpFOK6ZIYgp6Gr3B97yibqU0iDj9oran/UY9/5R7hV+e0QkmQQeHMiw7F+QXB+nxGBav+4IvjwxbHoK4n0QXFC7fZ/wBxNGqvPZiLaFLhpFDa7/dDpWaVIgb8PeHn3TMX4bcXirP9vLzPc2Veee6vB3uK7ZFTapeTGP5hqRzboJl5ZG/SwX4COFCKRdjK0Hkgpp8ANAJjcsgX7gyIoSCG37Gt2Rm3NmyU7+N0u8GjSTljXm8hqNtKW0veA/eQ43SzEzM2nWyu5jQBGNJYZ2DjI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
