travis:
  secure:
    BINSTAR_TOKEN: bCy206Qkm9pZt0I2c/efpiD4voIe7071kTYrSRnX1Y7GBFVRVmMAWeKYDR1WuCz2lLD8PcTfys3L2iCu4vL3v+BiQDQ85drTDYskPfzysPbWSfTTyVYFOyU5v7kJH3am+VWDcoGWEaCNThv2lJ+Nbf6GVsExVv0vT/0+No5uBKfVg/giDJ+ZUr/br+9wAHHZYUsmwU9HUGOu85B22l4VUkiLWuJ0YxonsTRJABpOK8sGNAa5jIEHx4IEkAC+5NaTdPJRf/ZmAYzDAdeybNaB0RjpHYFDzLfk3P4BGa07vUxGvPHNcH5CuDYsT6j54Qc1T3OSSlg1BtVUrT5FjOq00JEb6GTmbcADl7sw6p8Jzc1bqx5HTZSVSAfYWUAkbUjjk2ATeR59TV5oqHZMcqcMgLIMlGvFof2MI7DHxT1BjxDTA91UrE4EFeEadIDn3/yRVorc+JaHuM6z9L6/M4+7lx+advKZPTBbdnEORsTp6RU4wd6WaNazJQRsFWigwLLsBu9iqJDw9/9KuVaAQ3sXu/MEKg7zAKW6YwnYUcz3v6EEYFNsnQYpL3nbpcWX29LaiGH41bUQSHcOpnSmASXDyLz21YZBcXeEb0b0XzozpCEbsA/oXnHYCFq6PV5dfXpEIy6gL1Is11rESQMkdFYDWoH0wuqi8bgluHq5aAIlWCY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
